### ISSUE TITLE
Retire PostalCodeStringComparer class

### ISSUE THREAD

**Issue by istanishev** [Cimpress-MCP/PostalCodes.Net#29]
This class is used to compare postal codes as strings. We should not compare just strings as they might have different formats. Comparing should be done only on postal codes for the same country and matching the same format.

A better way would be to use postal code classes for comparison.

**Comment by rnowosielski** [comment]
This is not used externally - this class is used to compare the underlying postal code string in the PostalCode class.

This comparer is internal, and used in:

PostalCode.cs:154
PostalCode.cs:168
PostalCode.cs:187

So I don't really know what to do with this ticket - it seems like the only thing to do would be to close it, because the mentioned class is not available externally outside of the package but only is the underlying code under the PostalCode class.

**Comment by istanishev** [comment]
Agree :)
